### ISSUE TITLE
Membership fails under high load

### ISSUE THREAD

**Issue by avkapustin** [tarantool/membership#13]
### Problem description

All network activity in SWIM protocol actually use main thread, so under high load memebers looks like 'dead', because they can't ack in expected timeout

We have C implementation of SWIM protocol in core tarantool, but it have next disadvantages:
- Only from 2.2 version
- As I understand, it use main thread too, so can be stuck under load too

So we need separate thread to perform network betwwen cluster members in SWIM protocol (especially for PING/ACK messages)

### Possible solutions and caveats

- First, we should define mean of 'dead' for cluster member. Actually, 'dead' means it cannot process any requests at reasonable time. If we extract network to separate thread, the 'dead' will mean - 'tarantool process is died at all'

- Second, if we re-implement network part in C (to extract into separate thread), it will looks like a porting a part of core tarantool SWIM implementation, ported to 1.10 release. May be better to ask core team to backport this functionality to 1.10?

- If we decide to create a fresh implementation, Lua+C:
    - separate thread in C to accept/send UDP dgrams
    - in this thread we should decode UDP messages, in case of PING message, send ACK
    - we need full duplex IPC between C and Lua parts (UNIX domain socket ?)
    - for other messages, we push them into Lua side
    - in Lua, we process protocol step and rest of handle message step, and push to C data which should be send to another members

**Comment by rosik** [comment]
I doubt that the problem you defined is actually a problem. What's bad in 'dead' membership status? What negative consequences does it have? It must be something about cartridge failover, but it should be discussed if appropriate context of fixing cartridge.

I'm sure it's fair enough to talk about non-responsive instance as of 'dead' one, especially taking into account all timeouts are adjustable.

**Comment by rosik** [comment]
@knazarov join discussion please. What problem are we solving?

**Comment by knazarov** [comment]
Membership protocol should be fast and relatively sensitive to situations where parts of the cluster crash or disconnect. Having to tune membership timeouts because you have you have blocking queries is just wrong. It lowers that sensitivity.

If you have long queries that are considered a problem, use watchdog module and terminate the instance after a certain amount of time. Otherwise you will get unreasonable "flaps" in log and probably even unwanted master->slave switches.

**Comment by rosik** [comment]
No doable thing defined. Discussion ended. Closing
