### ISSUE TITLE
Memory leak by broadcast() method

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/membership#28]
The broadcast method uses the [`getifaddrs`](https://github.com/tarantool/membership/blob/9e33be32967fdb6070c45c05a4d39a3d20d13aad/membership/network.lua#L96) function. The `getifaddrs` function returns a table with allocated buffers in sic memory, but they are not cleared anywhere.

On a virtual machine with 10+ interfaces, a couple of MB of memory may leak.

**Comment by olegrok** [comment]
Memory allocated by ffi.new couldn't be freed manually. It automatically GCed as any LuaJIT cdata object.

However, since this buffer is used temporary without yields as optimization it could be allocated only once.
