### ISSUE TITLE
feature request: Support IPV6 : listen to ipv6 port and connect to ipv6 port of member 

### ISSUE THREAD

**Issue by Fedora7** [tarantool/membership#46]
use case: running tarantool cluster across different networks at different locations. Port forwarding setting at different routers is either not available/ no permission or not possible because the NAT ipv4 address of device is dynamic/changing. IPV6 firewall rules based on ipv6 network prefix is easier for this case.

**Comment by filonenko-mikhail** [comment]
Unfortunately no capacity right now for such feature. Gently closing.
